title: "روزنوشت‌های من"
motto: "یادداشت های یک بیمار کنجکاو"
author: Amir Asiaee
email: asiae002@umn.edu
url: # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog
keywords: everything
copyright: "Commons Attribution 4.0 International"
robot: 
description: > # this means to ignore newlines
  یادداشت های شخصی راجع به ... 
long_description: >
  سن و سال که بالا میره حتی تو دار ترین آدم ها ابایی از ابراز ندارند.
  
  قوی ترین عضله پیرمرد ها زبانه و سرگرمیشون پر حرفی
  
  نوشته های اینجا نشانه ی پیریه

favicon: assets/img/favicon.png
permalink: :title.html
#timezone: Europe/Berlin

paginate: 3
paginate_path: /page:num/

tag_page_layout: tag_page
tag_page_dir: tag

collections:
  projects:
    output: true

comment_system: static # or disqus. Default is no comments.
#disqus_shortname: mehdix
#google_analytics_id: UA-57282325-1
feedburner_id: REPLACE_WITH_YOUR_FEEDBURNER_ID

lang: fa_IR
twitter:
  username: aasiaeet
github:
  username: aasiaeet
  repository: mycancerandifa
# Footer logo will disappear if not set.
#logo: assets/img/me.png

exclude:
- scripts
- cache
- .bundle
- .sass-cache
- reply-mail-hook
- vendor
- CONTRIBUTING.md
- netlify.toml
- wercker.yml
- LICENSE
- env.sh
- screenshot.png
- jekyll-theme-mehdix-rtl.sublime-project
- jekyll-theme-mehdix-rtl.sublime-workspace
- travis.yml
- jekyll-theme-mehdix-rtl.gemspec
- rebuild_comments.py
- README.md
- Gemfile
- Gemfile.lock
